openapi: 3.0.3
info:
  title: EduSync Auth Service (Stub)
  version: 0.1.0
paths:
  /auth/register:
    post:
      summary: Register user (stub)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
                firstName:
                  type: string
                lastName:
                  type: string
      responses:
        '201':
          description: Created
  /auth/login:
    post:
      summary: Login (stub)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  format: email
                password:
                  type: string
      responses:
        '200':
          description: OK
